name: 'Clickhouse db cluster with ZooKeeper'
description: 'This Action will create a clickhouse db cluster with 2 shards / 2 replica with zookeeper'
author: vishnudxb
branding:
  icon: 'database'  
  color: 'yellow'
runs:
  using: 'docker'
  image: 'Dockerfile'

