on: [push]

jobs:
  test-clickhouse-db-action:
    runs-on: ubuntu-latest
    name: Testing clickhouse db action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Testing clickhouse db action
        uses: ./ # Uses an action in the root directory
